### ISSUE TITLE
add jaminan kendaraan, muncul notifikasi error data alamat, tetapi data berhasil tersimpan dan tanpa error.log

### ISSUE THREAD

**Issue by agilma** [ThunderID/KoperasiPro-5.4-#63]
![screen shot 2017-04-10 at 9 20 17 am](https://cloud.githubusercontent.com/assets/4099329/24843865/e42afdc6-1dd0-11e7-9a5b-0ef690a3ab15.png)

**Comment by chelsymooy** [comment]
seharusnya alamat itu isinya array, tapi data parsing seri, buat alamat jadi string *rolling eye
