### ISSUE TITLE
box search cut off some letter

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/KoperasiPro-5.4-#8]
Sepertinya padding box-search terlalu banyak. jadi beberapa huruf seperti 'g', 'y', dan 'j' terpotong.

![screenshot from 2017-02-16 08-19-25](https://cloud.githubusercontent.com/assets/5895063/23003151/57d19fa2-f421-11e6-95ab-2ff63174bffa.png)

**Comment by budi7** [comment]
fixed
